spring:
  datasource:
    url: jdbc:mysql://neomysql.mysql.database.azure.com:3306;useSSL=true&requireSSL=false;
    username: neo
    password: 9794740021@Rahul
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQL57Dialect

server:
  port: 9191


