spring:
  datasource:
    url: jdbc:sqlserver://neo-server.database.windows.net:1433;database=neodb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: neo
    password: 9794740021@Rahul
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


